<?php

namespace Tests\Mixins;

trait InteractWithMealDbEntities
{
    public function mealsDataProvider(): array
    {
        return [
            [
                'idMeal' => '53061',
                'strMeal' => 'Fresh sardines',
                'strDrinkAlternate' => null,
                'strCategory' => 'Side',
                'strArea' => 'Croatian',
                'strInstructions' => '::description::',
                'strMealThumb' => 'https://www.themealdb.com/images/media/meals/nv5lf31628771380.jpg',
                'strTags' => 'Fresh',
                'strYoutube' => 'https://www.youtube.com/watch?v=DDaZoXP1Mdc',
                'strIngredient1' => 'Sardines',
                'strIngredient2' => 'Vegetable Oil',
                'strIngredient3' => 'Flour',
                'strIngredient4' => 'Salt',
                'strIngredient5' => ' ',
                'strIngredient6' => '',
                'strMeasure1' => '500g',
                'strMeasure2' => 'Dash',
                'strMeasure3' => 'To Glaze',
                'strMeasure4' => 'Dash',
                'strMeasure5' => ' ',
                'strSource' => 'https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/',
                'strImageSource' => null,
                'strCreativeCommonsConfirmed' => null,
                'dateModified' => null,
            ],
            [
                'idMeal' => '52977',
                'strMeal' => 'Corba',
                'strDrinkAlternate' => null,
                'strCategory' => 'Side',
                'strArea' => 'Turkish',
                'strInstructions' => '::description::',
                'strTags' => 'Soup',
                'strYoutube' => 'https://www.youtube.com/watch?v=VVnZd8A84z4',
                'strIngredient1' => 'Lentils',
                'strIngredient2' => 'Onion',
                'strIngredient3' => 'Carrots',
                'strIngredient4' => 'Tomato Puree',
                'strIngredient5' => 'Cumin',
                'strIngredient6' => 'Paprika',
                'strIngredient7' => 'Mint',
                'strIngredient8' => 'Thyme',
                'strIngredient9' => 'Black Pepper',
                'strIngredient10' => 'Red Pepper Flakes',
                'strIngredient11' => 'Vegetable Stock',
                'strIngredient12' => 'Water',
                'strIngredient13' => 'Salt',
                'strIngredient14' => '',
                'strIngredient15' => '',
                'strMeasure1' => '1 cup ',
                'strMeasure2' => '1 large',
                'strMeasure3' => '1 large',
                'strMeasure4' => '1 tbs',
                'strMeasure5' => '2 tsp',
                'strMeasure6' => '1 tsp ',
                'strMeasure7' => '1/2 tsp',
                'strMeasure8' => '1/2 tsp',
                'strMeasure9' => '1/4 tsp',
                'strMeasure10' => '1/4 tsp',
                'strMeasure11' => '4 cups ',
                'strMeasure12' => '1 cup ',
                'strMeasure13' => 'Pinch',
                'strMeasure14' => ' ',
                'strMeasure15' => ' ',
                'strMeasure16' => ' ',
                'strSource' => 'https://findingtimeforcooking.com/main-dishes/red-lentil-soup-corba/',
                'strImageSource' => null,
                'strCreativeCommonsConfirmed' => null,
                'dateModified' => null,
            ],
        ];
    }
}
